### ISSUE TITLE
ext-intl must be required in composer.json

### ISSUE THREAD

**Issue by mbaumgartl** [laminas/laminas-mail#175]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.15.1

#### Summary

I updated laminas/laminas-mail in a small application. Afterwards I could not send emails.

#### Current behavior

This component generates a fatal error:

```
Fatal error:  Uncaught Error: Undefined constant "Laminas\Mail\Header\IDNA_ERROR_EMPTY_LABEL" in /var/www/html/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php:295
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php(135): Laminas\Mail\Header\AbstractAddressList->idnToAsciiViaPunycode('example.com')
#1 /var/www/html/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php(162): Laminas\Mail\Header\AbstractAddressList->idnToAscii('example.com')
#2 /var/www/html/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php(221): Laminas\Mail\Header\AbstractAddressList->getFieldValue(true)
#3 /var/www/html/vendor/laminas/laminas-mail/src/Headers.php(491): Laminas\Mail\Header\AbstractAddressList->toString()
#4 /var/www/html/public/test.php(11): Laminas\Mail\Headers->toString()
#5 {main}
  thrown in /var/www/html/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php on line 295
```

I think it was introduced in d75a9b29f3ad1bb6ab0e3c58e01bc5f48721e69c.

#### How to reproduce

```php
<?php
require_once 'vendor/autoload.php';

(Laminas\Mail\Headers::fromString('To: foo@example.com'))
    ->setEncoding('UTF-8')
    ->toString();
```

#### Expected behavior

Headers should be converted to strings w/o fatal error.

**Comment by ghostwriter** [comment]
hey @mbaumgartl, thanks for reporting this issue.

I believe`ext-intl` is **NOT** required in `composer.json` because 
we use [`true/punycode`](https://github.com/true/php-punycode) when `ext-intl` is not loaded.

the fatal error you experienced was caused by:
 "**Undefined constant** `Laminas\Mail\Header\IDNA_ERROR_EMPTY_LABEL`".

this means we need to `define()` the required constants
when `ext-intl` is not loaded/installed or use polyfill [`symfony/polyfill-intl-idn`](https://github.com/symfony/polyfill-intl-idn).
